class Languages {
  static var english_objects = {
    'property_text': 'Security',
    'management_app': 'System',
    'm_portal':'Management Portal',
    'app': 'app',
    'signIn': 'Sign in',
    'login': 'Login',
    'qrHome': 'Doorman',
    'access_to_camera': 'This app will require access to camera',
    'logout': 'Logout',
    'back': "Back",
    'checkIn': "Check In",
    'subscribeNewsLetter': "Subscribe to our news letter",
    'scan': 'Scan ',
    'qr': 'qr code',
    'history': 'History',
    'historyText': 'This feature keeps your history to maintain data',
    'checkOut':'Check Out',
    'doorman':'Doorman',
    'visitor':'Visitor',
    'check_in':'Check in',
    'check_out':'Check out',
    'placeQr':
        'Kindly place QR Code below within the frame to scan, and try to avoid shake to get results quickly.',
    'manageVisitorsData': 'Manage and Track your visitors data.',
    'provideYourEmail': 'Provide your email and password to proceed to your',
    'provideChangeEmail': 'Provide your email and password to proceed to your',
    'pMportal':'Security System',
    'dashboard':'Dashboard',
    'buildings':'Buildings',
    'visitor':"Visitor's QR",
    'settings':'Settings',
    'loginScreen':'Login Screen',
    't_dmn':'Total Doorman',
    't_bdings':'Total Buildings',
    't_visitors':'Total Visitors',
    'search_doorman_building':'Search Doorman',
    'search_building':'Search building',
    'search':'Search',
    'add_building':'Add Building',
    'details_building':'Please provide the follwing details to add the building',
    'details_doorman':'Please provide the follwing details to add and assign building',
    'building_name':'Select Building',
    'address':'Address',
    'add_doorman':'Add Doorman',
    'cancel':'Cancel',
    'save':'Save',
    'doorMan':'Doorman Name',
    'userName':'User Name',
    'pswrd':'Password',
    'pswrd2':'Password',
    'pic':'Picture',
    'mNum':'Mobile Number',
    'idNum':'ID card Number',
    'filter':'Filters',
    'status':'Status',
    'active':'Active',
    'inActive':'Inactive',
    'dName':'Userame',
    'dBname':'Building Name',
    'dUname':'User Name',
    'dMnum' : 'Mobile Number',
    'IdNum' : 'ID Number',
    'status':'Status',
    'clear':"Clear",
    'date':'Date',
    'doormen':'Doormen',
    'date_range':'Date Range',
    'pleaseAddDoorman':'Please Add a Building First',
    'buildingAdditionIsMandatory':'Building addition is mandatory because a doorman should be assigned to at least one building.',
    'credChSuccess':'Credentials changed successfully',
    'errorOccuredCD': "Some error occured. Please contact developer",
    'chCred':'Change Credentials',
    'chNow':'Change Now',
    'sure':'Are you sure to delete this element?',
    'recordsFound':'Records Found are:',
    'bActive':'Building will be Active',
    'bInactive':'Building will be Inactive',
    'email':'Email',
    'exportCV':'Export CV',
    'no.':'No. ',
    "email/pass can't be empty":"Email or password can't be empty",
    "email/pass is wrong":"Email or password is wrong, Please Try Again!",
    'pressLogoutButtonToExit':"Please press LogOut button in the settings page to Exit",
    'areyouSureTOChangeCredentials':"Are you sure to change previous credentials to these new Credentials?",
    'yourNewCredentials':"Your new Credentials",
    'email: ':'Email: ',
    'pass: ':'Password: ',
    'yes':'YES',
    'no':'NO',
    'formIsNotValidated':'Form Is not Validated'

  };
  static var test_objects = {
    'property_text':'test',
    'management_app':'test',
    'm_portal':'test',
    'app':'test',
    'signIn':'test',
    'login':'test',
    'qrHome':'test',
    'access_to_camera':'test',
    'logout':'test',
    'back':'test',
    'checkIn':'test',
    'subscribeNewsLetter':'test',
    'scan':'test',
    'qr':'test',
    'history':'test',
    'historyText':'test',
    'checkOut':'test',
    'doorman':'test',
    'visitor':'test',
    'check_in':'test',
    'check_out':'test',
    'placeQr':'test',
    'manageVisitorsData':'test',
    'provideYourEmail':'test',
    'provideChangeEmail':'test',
    'pMportal':'test',
    'dashboard':'test',
    'buildings':'test',
    'visitor':'test',
    'settings':'test',
    'loginScreen':'test',
    't_dmn':'test',
    't_bdings':'test',
    't_visitors':'test',
    'search_doorman_building':'test',
    'search_building':'test',
    'search':'test',
    'add_building':'test',
    'details_building':'test',
    'details_doorman':'test',
    'building_name':'test',
    'address':'test',
    'add_building':'test',
    'add_building_w':'test',
    'add_doorman':'test',
    'cancel':'test',
    'save':'test',
    'doorMan':'test',
    'userName':'test',
    'pswrd':'test',
    'pswrd2':'test',
    'pic':'test',
    'mNum':'test',
    'idNum':'test',
    'filter':'test',
    'status':'test',
    'active':'test',
    'inActive':'test',
    'dName':'test',
    'dBname':'test',
    'dUname':'test',
    'dMnum' :'test',
    'IdNum' :'test',
    'status':'test',
    'clear':'test',
    'date':'test',
    'doormen':'test',
    'date_range':'test',
    'pleaseAddDoorman':'test',
    'buildingAdditionIsMandatory':'test',
    'credChSuccess':'test',
    'errorOccuredCD':'test',
    'chCred':'test',
    'chNow':'test',
    'sure':'test',
    'recordsFound':'test',
    'bActive':'test',
    'bInactive':'test',
    'email':'test',
    'exportCV':'test',
    'no.':'test',
    "email/pass can't be empty":"test",
    "email/pass is wrong":"test",
    'pressLogoutButtonToExit':"test",
    'areyouSureTOChangeCredentials':"test",
    'yourNewCredentials':"test",
    'email: ':'test: ',
    'pass: ':'test: ',
    'yes':'test yes',
    'no':'test no',
    'formIsNotValidated':'Form Is not Validated test '
  };
  static var french_objects = {
  'property_text': 'propiedades',
  'management_app': 'app administración',
  'm_portal':'Portal de Administración',
  'app': 'app',
  'signIn': 'Sign in',
  'login': 'iniciar sesión',
  'qrHome': 'qr+home',
  'access_to_camera': 'Esta aplicación requerirá acceso a la cámara',
  'logout': 'cerrar sesión',
  'back': "atrás",
  'checkIn': "registrarse",
  'subscribeNewsLetter': "suscribirse a nuestro Boletín Informativo",
  'scan': 'Escanear ',
  'qr': 'Código qr',
  'history': 'Historia',
  'historyText': 'Esta característica mantiene su historia para mantener los datos',
  'checkOut': 'cerrar sesión',
  'doorman': 'Conserje',
  'visitor':'Visita',
  'check_in':'registrarse',
  'check_out':'cerrar sesión',
  'placeQr':'Por favor ubique el Código QR que aparece abajo dentro del recuadro para su escaneo, evitando temblar para obtenerlo rápido.',
  'manageVisitorsData': 'Administre y monitoree datos de sus visitas.',
  'provideYourEmail': 'Proveer su correo electrónico para proceder a su',
  'provideChangeEmail': 'Proveer su Correo Electrónico y Clave para proceder a su',
  'pMportal':'Portal de Administración de Condominios y Edificios',
  'dashboard':'Tablero',
  'buildings':'edificios',
  'visitor':"QR para visita",
  'settings':'Ajustes',
  'loginScreen':'iniciar sesión',
  't_dmn':'Total Guardia',
  't_bdings':'Total Edificios',
  't_visitors':'Total Visitas',
  'search_doorman_building':'Buscar Guardia',
  'search_building':'Buscar edificio',
  'search':'buscar',
  'add_building':'Agregar Edificio',
  'details_building':'Por favor otorgue los siguientes detalles para agregar un edificio',
  'details_doorman':'Por favor otorgue los siguientes detalles para agregar y asignar un edificio',
  'building_name':'Seleccionar Edificio',
  'address':'Dirección',
  'add_building':'Agregar edificio',
  'add_building_w':'Agregar edificio',
  'add_doorman':'Agregar Guardia',
  'cancel':'Cancelar',
  'save':'salvar',
  'doorMan':'Nombre del Guardia',
  'userName':'Nombre de Usuario',
  'pswrd':'Clave',
  'pswrd2':'Clave',
  'pic':'Foto',
  'mNum':'Número de Celular',
  'idNum':'Número de tarjeta ID',
  'filter':'Filtros',
  'status':'Estatus',
  'active':'Activo',
  'inActive':'Inactivo',
  'dName':'Usuario',
  'dBname':'Nombre de Edificio',
  'dUname':'Usuario',
  'dMnum' : 'Número de celular',
  'IdNum' : 'Número de ID',
  'status':'Estatus',
  'clear':"limpiar",
  'date':'Fecha',
  'doormen':'Guardia',
  'date_range':'Rango de fechas',
  'pleaseAddDoorman':'Por favor agregar primero un edificio',
  'buildingAdditionIsMandatory':'Añadir un edificio es obligatorio puesto que un Guardia/Conserje debe ser asignado a por lo menos un edificio',
  'credChSuccess':
  'Las credenciales se cambiaron exitosamente',
  'errorOccuredCD': 'Ocurrió un error. Por favor contactar al Desarrollador',
  'chCred':'Cambio de Credenciales',
  'chNow':'Cambio Ahora',
  'sure': 'Está seguro de eliminar este elemento?',
  'recordsFound':'Registros encontrados son:',
  'bActive':'El Edificio estará Activo',
  'bInactive':  'El Edificio estará Inactivo',
  'email':'Correo electrónico',
  'exportCV':'Exportar CV',
  'no.':'No. ',
  "email/pass can't be empty":'Correoelectrónico/clave no puede estar vacío',
  "email/pass is wrong":"El Correoelectrónico/Clave está equivocado, intente nuevamente",
  'pressLogoutButtonToExit':"Pulsar el botón de Cierre de Sesión en página de ajustes para salir",
  'areyouSureTOChangeCredentials':"Está seguro de cambiar las anteriores credenciales a estas nuevas?",
  'yourNewCredentials':"Sus nuevas credenciales",
  'email: ':'Correo electrónico: ',
  'pass: ':'Clave: ',
  'yes':'Sí',
  'no':'NO',
  'formIsNotValidated':'El Formulario no está validado'
  };

  static var skeleton_language_objects = {
    "english": english_objects,
    "urdu":test_objects,
    "french":french_objects,
  };
}
